name: 'MSbuild C/C++ CI'

on:
  push:
    branches: 
      - master
      - CI-CD
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
          
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: msbuild PixElv.sln -t:rebuild -verbosity:minimal -property:Configuration=Release

      - name: Test Compressed
        run: ./x64/Release/PixElv.exe -delay 0 -comp 1 -frames 15

      - name: Test Raw
        run: ./x64/Release/PixElv.exe -delay 0 -comp 0 -frames 1

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: PixElv-x64
          path: ./x64/Release/PixElv.exe
