name: 'MSbuild C/C++ CI'

on:
  push:
    branches: ['*']
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Generate version
        run: |
          $gitHash = git rev-parse HEAD
          $gitTag = git describe --tags --always --dirty
          @"
          #pragma once
          #define GIT_HASH "$gitHash"
          #define GIT_TAG "$gitTag"
          "@ | Out-File -FilePath git_info.h -Encoding ascii
          
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: msbuild PixElv.sln -t:rebuild -verbosity:minimal -property:Configuration=Release

      - name: Test Compressed
        run: ./x64/Release/PixElv.exe -delay 0 -comp 1 -frames 60

      - name: Test Raw
        run: ./x64/Release/PixElv.exe -delay 0 -comp 0 -frames 2

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: PixElv-x64
          path: ./x64/Release/PixElv.exe
